---
# Install dependencies on the host
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ["pip", "openstacksdk"]
    state: latest
# pip install --upgrade pip && pip install openstacksdk

- name: Install additional packages
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

