version: '3'

services:
  couch_master:
    image: couchdb:3.2.1
    restart: always
    ports:      
      - "5984:5984"     
      - "5986:5986"      
      - "4369:4369"      
      - "9100-9200:9100-9200"    
    links:      
      - couch_slave1      
      - couch_slave2
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      NODENAME: 172.26.128.215
      ERL_FLAGS: "-name \"couchdb@172.26.128.215\""
    container_name: couch_master
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      couchdb_network:
        ipv4_address: 172.26.128.215

  couch_slave1:
    image: couchdb:3.2.1
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      NODENAME: 172.26.128.179
      ERL_FLAGS: "-name \"couchdb@172.26.128.179\""
    container_name: couch_slave1
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      couchdb_network:
        ipv4_address: 172.26.128.179

  couch_slave2:
    image: couchdb:3.2.1
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      NODENAME: 172.26.132.88
      ERL_FLAGS: "-name \"couchdb@172.26.132.88\""
    container_name: couch_slave2
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      couchdb_network:
        ipv4_address: 172.26.132.88

volumes:
  couchdb_data:

networks:
  couchdb_network:
    ipam:
      config:
        - subnet: 172.26.0.0/16
