---
- name: Set up environment
  become: yes
  block:
    - name: Install dependencies
      apt:
        name:
          [
            "gnupg",
            "ca-certificates",
            "curl",
            "software-properties-common",
            "python3-dev",
            "python3-pip",
            "python3-setuptools",
          ]
        state: latest
        install_recommends: no
        update_cache: yes

    - name: Add Docker apt repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository and update apt cache
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        mode: "644"
        update_cache: yes
        state: present

    - name: Install docker
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
        state: latest
        install_recommends: no
        update_cache: yes

    - name: Install docker-compose
      pip:
        name: ["docker-compose"]
        state: latest
