- name: Run couchdb-setup.sh on each slave node
  ansible.builtin.script: couchdb-setup.sh
  args:
    executable: /bin/bash
  environment:
    NODES: "{{ nodes }}"
    USERNAME: "{{ username }}"
    PASSWORD: "{{ password }}"
  register: script_output
  when: "'melbourne_research_cloud_slaves' in group_names"

- name: Display script output (Run couchdb-setup.sh on each slave node)
  ansible.builtin.debug:
    var: script_output.stdout_lines
  when: "'melbourne_research_cloud_slaves' in group_names"

- name: Run couchdb-setup.sh on master node
  ansible.builtin.script: couchdb-setup.sh
  args:
    executable: /bin/bash
  environment:
    NODES: "{{ nodes }}"
    USERNAME: "{{ username }}"
    PASSWORD: "{{ password }}"
  register: script_output
  when: "'melbourne_research_cloud_master' in group_names"

- name: Display script output (Run couchdb-setup.sh on master node)
  ansible.builtin.debug:
    var: script_output.stdout_lines
  when: "'melbourne_research_cloud_master' in group_names"

