# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: default  # key-pairs
instance_network: qh2-uom-internal

# uom.mse.1c4g # 1 cores, 4.5 GB memory, 30 GB disk
# uom.mse.2c9g # 2 cores, 9 GB memory, 30 GB disk
flavor:
  - uom.mse.1c4g
  - uom.mse.2c9g

# Volume
volumes:
  - vol_name: harvester-1
    vol_size: 7
  - vol_name: harvester-2
    vol_size: 7
  - vol_name: harvester-3
    vol_size: 7

# Security group
security_groups:
  - name: group-64-2
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: group-64-2
    description: "HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: group-64-2
    description: "Erlang node access"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: group-64-2
    description: "Couchdb access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix:


# Instance
instances:
  - name: harvester-1
    flavor: "uom.mse.1c4g"
    volumes: ["harvester-1"]
  - name: harvester-2
    flavor: "uom.mse.1c4g"
    volumes: ["harvester-2"]
  - name: harvester-3
    flavor: "uom.mse.1c4g"
    volumes: ["harvester-3"]
