# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: default  # key-pairs
instance_network: qh2-uom-internal

# uom.mse.1c4g # 1 cores, 4.5 GB memory, 30 GB disk
# uom.mse.2c9g # 2 cores, 9 GB memory, 30 GB disk
flavor:
  - uom.mse.1c4g
  - uom.mse.2c9g

# Volume
volumes:
  - vol_name: webapp
    vol_size: 50
  - vol_name: harvester-1
    vol_size: 150
  - vol_name: harvester-2
    vol_size: 150
  - vol_name: harvester-3
    vol_size: 150

# Security a group
security_groups:
  - name: group-64-2
    description: "default"
    ether_type: IPv6
    protocol: any
    direction: egress
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: ::/0
  - name: group-64-2
    description: "default"
    ether_type: IPv4
    protocol: any
    direction: egress
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: group-64-2
    ether_type: IPv4
    description: "SSH access"
    protocol: tcp
    direction: ingress
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    remote_security_group: "-"
  - name: group-64-2
    description: "HTTP access"
    ether_type: IPv4
    protocol: tcp
    direction: ingress
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: group-64-2
    description: "All Engress"
    ether_type: IPv4
    protocol: tcp
    direction: egress
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  


# Instance
instances:
  - name: webapp
    flavor: "uom.mse.2c9g"
    volumes: ["webapp"]
  - name: harvester-1
    flavor: "uom.mse.2c9g"
    volumes: ["harvester-1"]
  - name: harvester-2
    flavor: "uom.mse.2c9g"
    volumes: ["harvester-2"]
  - name: harvester-3
    flavor: "uom.mse.2c9g"
    volumes: ["harvester-3"]
