---
- name: Copy the script to the remote server
  hosts: melbourne_research_cloud
  become: yes
  tasks:
    - name: Copy the script to the remote server
      ansible.builtin.copy:
        src: couchdb-setup.sh
        dest: /tmp/couchdb-setup.sh
        mode: 0755

- name: Set up CouchDB cluster on slave node
  hosts: melbourne_research_cloud_slaves
  gather_facts: yes
  become: yes
  tasks:
    - name: Run the script on each instance
      ansible.builtin.shell: /tmp/couchdb-setup.sh
      args:
        executable: /bin/bash
      environment:
        NODES: "{{ nodes }}"
        USERNAME: "{{ username }}"
        PASSWORD: "{{ password }}"
      register: script_output
    - name: Display script output
      ansible.builtin.debug:
        var: script_output.stdout_lines

- name: Set up CouchDB cluster on master nodes
  hosts: melbourne_research_cloud_master
  gather_facts: yes
  become: yes
  tasks:
    - name: Run the script on each instance
      ansible.builtin.shell: /tmp/couchdb-setup.sh
      args:
        executable: /bin/bash
      environment:
        NODES: "{{ nodes }}"
        USERNAME: "{{ username }}"
        PASSWORD: "{{ password }}"
      register: script_output
    - name: Display script output
      ansible.builtin.debug:
        var: script_output.stdout_lines

        