version: '3'
services:
  nginx: 
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "3050:80"
  api:
      build:
        context: ./webapp_server
        dockerfile: dockerfile
      volumes:
        - /app/node_modules
        - ./webapp_server:/app
  client: 
   stdin_open: false
   build:   
    context: ./webapp_client
    dockerfile: dockerfile
   volumes:
     - /app/node_modules
     - ./webapp_client:/app