version: '3'
services:
  nginx: 
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
      build:
        context: ./webapp_server
        dockerfile: Dockerfile
      volumes:
        - /app/node_modules
        - ./webapp_server:/app
  client: 
   stdin_open: true
   environment:
      - CHOKIDAR_USEPOLLING=true
   build:   
    context: ./webapp_client
    dockerfile: Dockerfile
   volumes:
     - /app/node_modules
     - ./webapp_client:/app