version: '3'
services:
  nginx: 
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
      build:
        dockerfile: dockerfile.dev
        context: ./webapp_server
      volumes:
        - /app/node_modules
        - ./server:/app
  client: 
   stdin_open: true
   environment:
    - CHOKDAR_USERPOLLING=true
   build:
    dockerfile: dockerfile.dev
    context: ./webapp_client
   volumes:
     - /app/node_modules
     - ./client:/app