version: '3'
services:
  shiny:
    build:
      context: ./myShinyApp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3838:3838
    volumes:
      - ./myShinyApp:/srv/shiny-server/

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shiny
